// import localFont from "next/font/local";
// import "./globals.css";
// import Header from "../../components/Header";
// import Footer from "../../components/Footer";

// import "../../style/theme.css";
// import getEnvironment from "../../utils/environment";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "../../style/landing.css";

// import SidebarLeft from "../../components/MojoInfinity/SidebarLeft";
// import { useState } from "react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Mojo Infinity",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <>
//       <html lang="en">
//         <head>
{
  /* <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          /> */
}

{
  /* <link
            rel="stylesheet"
            href="https://sandbox-st.mojoinfinity.com/css/landing.css"
          /> */
}
{
  /* <link
            rel="stylesheet"
            href="https://sandbox-st.mojoinfinity.com/css/kyc.css"
          /> */
}
{
  /* <link
            rel="stylesheet"
            href="https://sandbox-st.mojoinfinity.com/css/mm-header/infinity-header.css"
          /> */
}
{
  /* <link
            rel="stylesheet"
            href="https://sandboxwealth-st.mojoinfinity.com/css/header.css"
          /> */
}

{
  /* <link
            rel="stylesheet"
            href="https://sandboxwealth-st.mojoinfinity.com/css/style.css"
          /> */
}
{
  /* <link
            rel="stylesheet"
            href="https://sandboxwealth-st.mojoinfinity.com/css/theme.css"
          /> */
}
{
  /* <link
            rel="stylesheet"
            href="https://sandboxwealth-st.mojoinfinity.com/css/style.css"
          /> */
}
{
  /* <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            crossOrigin="anonymous"
          ></link> */
}
// </head>

{
  /* <SidebarRight
          isOpen={isRightSidebarOpen}
          onClose={() => setIsRightSidebarOpen(false)}
        /> */
}
//     <body
//     // className={`${geistSans.variable} ${geistMono.variable}`}
//     >
//       <div className="pageconetnt">
//         <Header />
//         {children}
//         <Footer />
//       </div>
//     </body>
//   </html>
// </>
// );
// }

import "./globals.css";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import Head from "next/head";

export const metadata = {
  title: "Mojo Infinity",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        /> */}
        {/* Add any other relevant links or meta tags here */}
      </Head>
      <html lang="en">
        <body>
          <main className="pagecontent">
            <Header />
            {children}
            <Footer />
          </main>
        </body>
      </html>
    </>
  );
}
